// Load playlist from songs.json (generated by scripts/generate_playlist.js)
const tracks = [];
const audio = document.getElementById('audio');
const ytContainer = document.getElementById('yt-player');
const titleEl = document.getElementById('title');
const artistEl = document.getElementById('artist');
const coverEl = document.getElementById('cover');
const playBtn = document.getElementById('play');
const prevBtn = document.getElementById('prev');
const nextBtn = document.getElementById('next');
const currentTimeEl = document.getElementById('currentTime');
const durationEl = document.getElementById('duration');
const progressBar = document.getElementById('progressBar');
const progressFilled = document.getElementById('progressFilled');
const volumeEl = document.getElementById('volume');
const repeatBtn = document.getElementById('repeat');
const playlistEl = document.getElementById('playlist');
const noSongsEl = document.getElementById('noSongs');
const volIconEl = document.getElementById('volIcon');

let current = 0;
let isPlaying = false;
let isRepeat = false;

// YouTube player state
let ytPlayer = null;
let ytReady = false;
let usingYT = false;
let ytPoll = null;

function sanitizeTitleFromPath(src){
  try{ const parts = src.split('/'); const fname = parts[parts.length-1]; return decodeURIComponent(fname.replace(/\.[^/.]+$/,'')); }
  catch(e){ return src; }
}

function isYouTubeUrl(u){
  if (!u) return false;
  return /(?:youtube.com\/watch\?v=|youtu.be\/)/i.test(u) || /^[A-Za-z0-9_-]{11}$/.test(u);
}

function extractYouTubeId(u){
  if (!u) return null;
  if (/^[A-Za-z0-9_-]{11}$/.test(u)) return u;
  const m = u.match(/[?&]v=([A-Za-z0-9_-]{11})/i) || u.match(/youtu\.be\/([A-Za-z0-9_-]{11})/i);
  return (m && m[1]) ? m[1] : null;
}

function showNoSongs(){ noSongsEl.style.display = 'block'; playBtn.disabled = true; prevBtn.disabled = true; nextBtn.disabled = true; }
function enableControls(){ noSongsEl.style.display = 'none'; playBtn.disabled = false; prevBtn.disabled = false; nextBtn.disabled = false; }

function updatePlaylistUI(index){ Array.from(playlistEl.children).forEach((li,i)=>{ li.classList.toggle('active', i===index); }); }

function createYTPlayer(videoId){
  if (!ytReady){
    setTimeout(()=>createYTPlayer(videoId), 200);
    return;
  }
  if (ytPlayer){
    try{ ytPlayer.loadVideoById(videoId); }catch(e){ ytPlayer.cueVideoById(videoId); }
    return;
  }
  ytPlayer = new YT.Player('yt-player', {
    height: '1', width: '1', videoId,
    playerVars: { 'controls': 0, 'rel': 0, 'iv_load_policy': 3 },
    events: {
      onReady: ()=>{},
      onStateChange: onYTStateChange
    }
  });
}

function onYTStateChange(e){
  if (e.data === 1){ // playing
    isPlaying = true; playBtn.textContent = '⏸'; playBtn.setAttribute('aria-label','Pause');
    startYTPoll();
  } else if (e.data === 2){ // paused
    isPlaying = false; playBtn.textContent = '▶'; playBtn.setAttribute('aria-label','Play');
    stopYTPoll();
  } else if (e.data === 0){ // ended
    stopYTPoll(); if (isRepeat) play(); else next();
  }
}

function startYTPoll(){ if (ytPoll) return; ytPoll = setInterval(()=>{
  if (!ytPlayer || typeof ytPlayer.getDuration !== 'function') return;
  const dur = ytPlayer.getDuration();
  const cur = ytPlayer.getCurrentTime();
  if (dur && !isNaN(dur)){
    const pct = (cur / dur) * 100;
    progressFilled.style.width = pct + '%';
    currentTimeEl.textContent = formatTime(cur);
    durationEl.textContent = formatTime(dur);
    progressBar.setAttribute('aria-valuenow', String(Math.round(pct)));
  }
}, 500); }
function stopYTPoll(){ if (ytPoll){ clearInterval(ytPoll); ytPoll = null; } }

function loadTrack(index){ if (!tracks.length) return; const t = tracks[index];
  const isYT = isYouTubeUrl(t.src);
  titleEl.textContent = t.title || sanitizeTitleFromPath(t.src);
  artistEl.textContent = t.artist || '';
  if (t.cover){ coverEl.hidden = false; coverEl.src = t.cover; } else { coverEl.hidden = true; coverEl.removeAttribute('src'); }

  updatePlaylistUI(index);

  if (isYT){
    usingYT = true;
    try{ audio.pause(); }catch(e){}
    const id = extractYouTubeId(t.src);
    createYTPlayer(id);
  } else {
    usingYT = false;
    try{ if (ytPlayer && typeof ytPlayer.stopVideo === 'function') ytPlayer.stopVideo(); }catch(e){}
    audio.src = t.src;
    audio.load();
  }
}

function play(){ if (!tracks.length) return; if (usingYT){ if (ytPlayer && typeof ytPlayer.playVideo === 'function'){ ytPlayer.playVideo(); } } else { audio.play(); } }
function pause(){ if (usingYT){ if (ytPlayer && typeof ytPlayer.pauseVideo === 'function') ytPlayer.pauseVideo(); } else { audio.pause(); } }
function togglePlay(){ isPlaying ? pause() : play(); }

function prev(){ if (!tracks.length) return; current = (current - 1 + tracks.length) % tracks.length; loadTrack(current); play(); }
function next(){ if (!tracks.length) return; current = (current + 1) % tracks.length; loadTrack(current); play(); }

function formatTime(sec){ const s = Math.floor(sec % 60).toString().padStart(2,'0'); const m = Math.floor(sec / 60); return `${m}:${s}`; }

// audio timeupdate (for local files)
audio.addEventListener('timeupdate', ()=>{ if (audio.duration && !usingYT){ const pct = (audio.currentTime / audio.duration) * 100; progressFilled.style.width = pct + '%'; currentTimeEl.textContent = formatTime(audio.currentTime); durationEl.textContent = formatTime(audio.duration); progressBar.setAttribute('aria-valuenow', String(Math.round(pct))); } });

progressBar.addEventListener('click', (e)=>{ const rect = progressBar.getBoundingClientRect(); const x = e.clientX - rect.left; const pct = x / rect.width; if (usingYT){ if (ytPlayer && typeof ytPlayer.seekTo === 'function'){ const dur = ytPlayer.getDuration(); if (dur) ytPlayer.seekTo(pct * dur, true); } } else { if (audio.duration) audio.currentTime = pct * audio.duration; } });

function updateVolumeUI(){
  const v = Number(volumeEl.value);
  const pct = Math.round(v * 100);
  volumeEl.style.setProperty('--pct', pct + '%');
  if (usingYT){
    if (ytPlayer && typeof ytPlayer.setVolume === 'function') ytPlayer.setVolume(pct);
  } else {
    audio.volume = v;
  }
  if (volIconEl){
    if (v === 0) volIconEl.textContent = '🔇';
    else if (v < 0.5) volIconEl.textContent = '🔈';
    else volIconEl.textContent = '🔊';
    volIconEl.classList.toggle('active', v >= 0.6);
  }
}

volumeEl.addEventListener('input', ()=>{ const v = Number(volumeEl.value); if (usingYT){ if (ytPlayer && typeof ytPlayer.setVolume === 'function') ytPlayer.setVolume(Math.round(v * 100)); } else { audio.volume = v; } updateVolumeUI(); });

playBtn.addEventListener('click', togglePlay);
prevBtn.addEventListener('click', prev);
nextBtn.addEventListener('click', next);

repeatBtn.addEventListener('click', ()=>{ isRepeat = !isRepeat; repeatBtn.setAttribute('aria-pressed', String(isRepeat)); repeatBtn.classList.toggle('active', isRepeat); });

audio.addEventListener('ended', ()=>{ if (isRepeat) play(); else next(); });

function buildPlaylistUI(){ playlistEl.innerHTML = ''; tracks.forEach((t,i)=>{ const li = document.createElement('li'); li.textContent = t.title || sanitizeTitleFromPath(t.src); li.addEventListener('click', ()=>{ current = i; loadTrack(i); play(); }); playlistEl.appendChild(li); }); }

function loadPlaylistFromJSON(){ fetch('songs.json').then(r=>{ if(!r.ok) throw new Error('no songs.json'); return r.json(); }).then(arr=>{ if (Array.isArray(arr) && arr.length){ tracks.splice(0,tracks.length,...arr); buildPlaylistUI(); enableControls(); current = 0; loadTrack(0); } else { showNoSongs(); } }).catch(e=>{ console.warn('Could not load songs.json', e); showNoSongs(); }); }

// initial load
loadPlaylistFromJSON();

// YouTube API ready callback (called by iframe API)
window.onYouTubeIframeAPIReady = function(){ ytReady = true; };

// keyboard: space toggles play
window.addEventListener('keydown', (e)=>{ if (e.code === 'Space' && document.activeElement.tagName !== 'INPUT') { e.preventDefault(); togglePlay(); }});

// set initial volume
audio.volume = Number(volumeEl.value);
updateVolumeUI();
repeatBtn.classList.toggle('active', isRepeat);

// Watermark protection: ensure the watermark element exists and re-insert if removed
(function ensureWatermark(){
  const id = 'watermark';
  function create(){
    const d = document.createElement('div');
    d.id = id;
    d.setAttribute('aria-hidden','true');
    d.textContent = 'Gokul S - 7376241CS186';
    document.body.appendChild(d);
  }
  if (!document.getElementById(id)) create();
  const mo = new MutationObserver(()=>{ if(!document.getElementById(id)) create(); });
  mo.observe(document.body, {childList:true, subtree:true});
})();